# Generated by Django 2.2.7 on 2019-11-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aparser', '0002_auto_20191112_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='published_date',
            field=models.DateTimeField(verbose_name='Дата публикации'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.TextField(blank=True, null=True, verbose_name='Валюта'),
        ),
    ]
