# Generated by Django 2.2.7 on 2020-01-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aparser', '0004_auto_20200118_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(1, 'Новое'), (2, 'Готово')], default=1, verbose_name='Статус задания'),
        ),
    ]
