# Generated by Django 2.2.7 on 2020-01-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aparser', '0005_auto_20200118_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.TextField(default='Задание', verbose_name='Название задания'),
        ),
    ]
