# Generated by Django 2.2.7 on 2020-01-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aparser', '0006_task_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.TextField(unique=True, verbose_name='Название задания'),
        ),
    ]
